name: Build Flutter APK

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL download project zip (Catbox)'
        required: true
      chat_id:
        description: 'Telegram chat ID (opsional)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download project from Catbox
        run: wget -O project.zip "${{ github.event.inputs.download_url }}"

      - name: Extract project
        run: unzip project.zip -d project

      - name: Setup Flutter 3.22.4 (Dart 3.8.5)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.4'

      - name: Get dependencies
        working-directory: ./project
        run: flutter pub get

      - name: Build APK release
        working-directory: ./project
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ./project/build/app/outputs/flutter-apk/app-release.apk
